### ISSUE TITLE
Problème comptage des animaux dans l'arche

### ISSUE THREAD

**Issue by chatelardfrancois** [caliendojulien/Noe#1]
Il me semble que tu comptes le nombres d'animaux chats, chiens, lapins et gorilles à la création de l'animal puisque l'incrementation se fait dans le constructeur de l'animal. Mais il se peut que l'animal créé ne soit pas ajouté à l'arche puisque la vérification intervient après la création. Dans ce cas l'animal n'est pas dans l'arche mais le compteur le prends en compte et affichera un nombre d'animaux, de cette espèce dans l'arche, erroné.

Et je suis pas sur non plus que le compteur nbAnimaux dans le constructeur animal soit utile puisque tu as fait une méthode qui compte le nombre d'animaux dans l'arche

**Comment by caliendojulien** [comment]
Je suis d’accord avec toi. 
je corrige ça dans le prochain commit.
